### ISSUE TITLE
Show timestamp of replaced tx

### ISSUE THREAD

**Issue by maflcko** [0xB10C/mempool-observer-fullrbf-ui#1]
I presume the event timestamp is when the replacement enters the mempool? Either way, I think it would be useful to also display when the replaced transaction entered the mempool.

**Comment by 0xB10C** [comment]
added. Will show up for all new replacements. Also noted here https://github.com/bitcoin/bitcoin/pull/26531#discussion_r1045624415.

![image](https://user-images.githubusercontent.com/19157360/207081229-d36c6d19-f12a-4131-bfe1-441192707004.png)
